version: "2"
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=proj
      - POSTGRES_DB=proj_production
    volumes:
      - proj-volume:/var/lib/postgresql/data
    networks:
      - proj-net

  back:
    image: proj/back
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - proj-net

  front:
    image: proj/front
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - proj-net

volumes:
  proj-volume:

networks:
  proj-net:
    driver: bridge